apiVersion: v1
kind: Service
metadata:
  name: webook-record
spec:
  selector:
    app: webook-record
  ports:
    - name: http
      protocol: TCP
      port: 98
      targetPort: 8081
  type: ClusterIP